apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-llm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-llm-app
  template:
    metadata:
      labels:
        app: cpu-llm-app
    spec:
      nodeSelector:
        accelerator: cpu
      volumes:
      # - name: cache-volume
      #   persistentVolumeClaim:
      #     claimName: llama-3.2-1b
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      # - name: shm
      #   emptyDir:
      #     medium: Memory
      #     sizeLimit: "1Gi"
      containers:
      - name: llama-3-2-1b
        image: openeuler/vllm-cpu:0.6.3-oe2403lts
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve meta-llama/Llama-3.2-1B -device=cpu -tp=2 --distributed-executor-backend mp"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: 8G
            # nvidia.com/gpu: "1"
          requests:
            cpu: "800m"
            memory: 5G
            # nvidia.com/gpu: "1"
        # volumeMounts:
        # - mountPath: /root/.cache/huggingface
        #   name: cache-volume
        # - name: shm
        #   mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5