apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: default
type: Opaque
data:
  token: "aGZfZVJIZ0lNZGZweWROS2d1SWZpbFl6bGxTSXBxVWR0WENWeg=="
  # token: "<base64-encoded-huggingface-token>"